#!/bin/sh /etc/rc.common

START=95
STOP=01

USE_PROCD=1
NAME=icwmp_notifd

start_service() {
        procd_open_instance
        procd_set_param command "/usr/sbin/icwmp_notifd"
        procd_close_instance
}

stop() {
        service_stop /usr/sbin/icwmp_notifd
}

service_triggers()
{
        procd_add_reload_trigger icwmp_notifd
}

reload_service() {
        stop
        start
}