#!/bin/sh
# Copyright (C) 2019 PIVA Software <www.pivasoftware.com>
# 	Author: AMIN Ben Ramdhane <amin.benramdhane@pivasoftware.com>


UCI_CONFIG_DIR="/etc/config/"
UCI_GET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state get"
UCI_SET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state set"

udpecho_get() {
	local val=`$UCI_GET_VARSTATE $1`
	echo ${val:-$2}
}

udpecho_launch() {
	local i res ba stc times sc1 success_count failure_count min_time avg_time max_time avg_time_sum min max micros
	[ "`$UCI_GET_VARSTATE cwmp.@udpechodiagnostic[0].DiagnosticState`" != "Requested" ] && return
	local host=`udpecho_get cwmp.@udpechodiagnostic[0].Host`
	local port=`udpecho_get cwmp.@udpechodiagnostic[0].port`
	local cnt=`udpecho_get cwmp.@udpechodiagnostic[0].NumberOfRepetitions 1`
	local dsize=`udpecho_get cwmp.@udpechodiagnostic[0].DataBlockSize 24`
	local dscp=`udpecho_get cwmp.@udpechodiagnostic[0].DSCP 0`
	local proto=`udpecho_get cwmp.@udpechodiagnostic[0].ProtocolVersion Any`
	local inter_time=`udpecho_get cwmp.@udpechodiagnostic[0].InterTransmissionTime 1000`
	local tos=$((dscp<<2))
	inter_time=$((inter_time/1000))
	[ "$inter_time" = "0" ] && inter_time="1"
	[ "$host" = "" ] && return
	[ "$port" = "" ] && return
	micros=1000
	success_count=0
	avg_time_sum=0
	min=9999999
	max=0
	i=0

	while [ $i -lt $cnt ]; do
		let i++
		[ "$proto" = "Any" ] && res=$(nping -c 1 --tos $tos --udp --dest-port $port --data-length $dsize $host 2>&1)
		[ "$proto" = "IPv4" ] && res=$(nping -4 -c 1 --tos $tos --udp --dest-port $port --data-length $dsize $host 2>&1)
		[ "$proto" = "IPv6" ] && res=$(nping -6 -c 1 --tos $tos --udp --dest-port $port --data-length $dsize $host 2>&1)
		ba=`echo "$res" | grep "RCVD"`
		[ -z "$ba" ] && { $UCI_SET_VARSTATE cwmp.@ippingdiagnostic[0].DiagnosticState=Error_CannotResolveHostName; return; }
		stc=`echo "$res" | grep "RCVD" | grep "unreachable"`
		[ -n "$stc" ] && { $UCI_SET_VARSTATE cwmp.@ippingdiagnostic[0].DiagnosticState=Error_Other; return; }
		times=`echo "$res" | grep "rtt"`
		[ -z "$times" ] && continue
		sc1=`echo "$res" | grep "Rcvd" | awk -F': ' '{print $3}' | awk -F'(' '{ print $1 }'`
		sc1=${sc1:-0}
		success_count=$((success_count+sc1))
		max_time=`echo $times | awk -F': ' '{ print $2 }' | awk -F'ms' '{ print $1 }'`
		min_time=`echo $times | awk -F': ' '{ print $3 }' | awk -F'ms' '{ print $1 }'`
		avg_time=`echo $times | awk -F': ' '{ print $4 }' | awk -F'ms' '{ print $1 }'`
		min_time=${min_time:-0}
		avg_time=${avg_time:-0}
		max_time=${max_time:-0}
		min_time=$(echo $min_time $micros | awk '{printf "%3.0f\n",$1*$2}')
		avg_time=$(echo $avg_time $micros | awk '{printf "%3.0f\n",$1*$2}')
		max_time=$(echo $max_time $micros | awk '{printf "%3.0f\n",$1*$2}')
		[ $min_time -lt $min ] && min=$min_time
		[ $max_time -gt $max ] && max=$max_time
		avg_time_sum=$((avg_time_sum+avg_time))
		sleep $inter_time
	done
	failure_count=$((cnt-success_count))
	[ $success_count -gt 0 ] && avg_time=$((avg_time_sum/success_count)) || avg_time=0
	min_time=$min
	max_time=$max
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].DiagnosticState=Complete
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].SuccessCount=$success_count
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].FailureCount=$failure_count
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].AverageResponseTime=$avg_time
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].MinimumResponseTime=$min_time
	$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].MaximumResponseTime=$max_time
	event_dignostic
}

event_dignostic() {
	local e=1
	local i=0
	while [ "$e" != 0 -a $i -lt 200 ]; do
		ubus -t 1 call tr069 inform '{"event":"8 DIAGNOSTICS COMPLETE"}' &>/dev/null
		e=$?
		[ "$e" != "0" ] && sleep 1;
		let i++
	done
}

udpecho_stop_diagnostic() {
	local pids=`ps | grep udpecho_launch | grep -v grep | awk '{print $1}'`
	if [ -n "$pids" ]; then
		kill -9 $pids &>/dev/null
		$UCI_SET_VARSTATE cwmp.@udpechodiagnostic[0].DiagnosticState=None
	fi
}

if [ "$1" == "run" ] ; then
	udpecho_launch  
elif [ "$1" == "stop" ]; then
	udpecho_stop_diagnostic
else
	return
fi
